apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-gateway-monitor
  namespace: issue-app
  labels:
    app: api-gateway
spec:
  selector:
    matchLabels:
      app: api-gateway
  namespaceSelector:
    matchNames:
      - issue-app
  endpoints:
    - port: http
      interval: 30s
      path: /actuator/prometheus
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: auth-service-monitor
  namespace: issue-app
  labels:
    app: auth-service
spec:
  selector:
    matchLabels:
      app: auth-service
  namespaceSelector:
    matchNames:
      - issue-app
  endpoints:
    - port: http
      interval: 30s
      path: /actuator/prometheus
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: issue-service-monitor
  namespace: issue-app
  labels:
    app: issue-service
spec:
  selector:
    matchLabels:
      app: issue-service
  namespaceSelector:
    matchNames:
      - issue-app
  endpoints:
    - port: http
      interval: 30s
      path: /actuator/prometheus
