apiVersion: v1
kind: ConfigMap
metadata:
  name: issue-service-config # 🟢 Leave this exactly as it is
  namespace: issue-app
data:
  # 🟢 DATABASE COUPLING FIX: Directing data traffic to the isolated issue_db schema
  SPRING_DATASOURCE_URL: jdbc:mysql://prod-issue-db.c8tsk48m85k3.us-east-1.rds.amazonaws.com:3306/issue_db