apiVersion: apps/v1
kind: Deployment
metadata:
  name: issue-service
spec:
  revisionHistoryLimit: 3
  replicas: 1
  selector:
    matchLabels:
      app: issue-service
  template:
    metadata:
      labels:
        app: issue-service
    spec:
      serviceAccountName: issue-app-sa
      containers:
        - name: issue-service
          image: issue-service:latest
          ports:
            - containerPort: 8098
          resources:
            requests:
              cpu: "100m"       
              memory: "256Mi"  
            limits:
              cpu: "500m"
              memory: "1Gi"    
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:+UseSerialGC -Xss256k -Xms256m -Xmx512m"
            # 🟢 PHYSICAL ISOLATION UPDATE: Routes directly to your dedicated Issue RDS hardware instance
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://prod-issue-db.c8tsk48m85k3.us-east-1.rds.amazonaws.com:3306/issue_db"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: issue-service-secrets
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: issue-service-secrets
                  key: SPRING_DATASOURCE_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: issue-service-secrets
                  key: JWT_SECRET
          volumeMounts:
            - name: storage
              mountPath: /data
      volumes:
        - name: aws-iam-token
          projected:
            defaultMode: 420
            sources:
              - id: sts
                serviceAccountToken:
                  audience: sts.amazonaws.com
                  expirationSeconds: 86400
                  path: token
        - name: storage
          emptyDir: {}