apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: api-gateway
  newName: 530352103493.dkr.ecr.us-east-1.amazonaws.com/prod-api-gateway
  newTag: fffaf3eea197df2e7e54fc710b1826d924833991
- name: auth-service
  newName: 530352103493.dkr.ecr.us-east-1.amazonaws.com/prod-auth-service
  newTag: fffaf3eea197df2e7e54fc710b1826d924833991
- name: frontend-service
  newName: 530352103493.dkr.ecr.us-east-1.amazonaws.com/prod-frontend-service
  newTag: fffaf3eea197df2e7e54fc710b1826d924833991
- name: issue-service
  newName: 530352103493.dkr.ecr.us-east-1.amazonaws.com/prod-issue-service
  newTag: fffaf3eea197df2e7e54fc710b1826d924833991
