apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: api-gateway
  newName: 530352103493.dkr.ecr.us-east-1.amazonaws.com/prod-api-gateway
  newTag: bf4b416123c8d24781ca0ceb0393e33fcacde49e
- name: auth-service
  newName: 530352103493.dkr.ecr.us-east-1.amazonaws.com/prod-auth-service
  newTag: bf4b416123c8d24781ca0ceb0393e33fcacde49e
- name: frontend-service
  newName: 530352103493.dkr.ecr.us-east-1.amazonaws.com/prod-frontend-service
  newTag: bf4b416123c8d24781ca0ceb0393e33fcacde49e
- name: issue-service
  newName: 530352103493.dkr.ecr.us-east-1.amazonaws.com/prod-issue-service
  newTag: bf4b416123c8d24781ca0ceb0393e33fcacde49e
